services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
        depends_on:
            - mariadb
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx_server
        ports:
            -"8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mariadb:
        image: 'mariadb:10.9'
        container_name: mariadb
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - laravel

    queue:
        build:
            context: .
        container_name: laravel_queue
        command: >
            supervisord -c /etc/supervisord.conf
        volumes:
            - .:/var/www/html
            - ./supervisord.conf:/etc/supervisord.conf
        depends_on:
            - app
        networks:
            - laravel

    cron:
        build:
            context: .
        container_name: laravel_cron
        volumes:
            - .:/var/www/html
            - ./crontab/laravel-cron:/etc/cron.d/laravel-cron
        command: ["cron", "-f"]
        networks:
            - laravel

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        container_name: redis
        restart: unless-stopped
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    laravel:
        driver: bridge

volumes:
    mariadb_data:
